### ISSUE TITLE
Need some guide to get started.

### ISSUE THREAD

**Issue by auvipy** [haypo/fatoptimizer#11]
I found this project on gsoc project last year. I want to know the status/plan with this project. If you think this is a project still worth I want your suggestions/guideline to get started and start some smaller contribution and move forward. @haypo

**Comment by haypo** [comment]
Sorry, I didn't work on FAT Python recently. The TODO list is probably
still up to date.

**Comment by auvipy** [comment]
OK. would you mind if i ping for help some times?

**Comment by haypo** [comment]
Nope, go ahead.

**Comment by auvipy** [comment]
thanks. my irc is auvipy too
